[project]
name = "lanedetection"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "norfair>=2.3.0",
    "opencv-python-headless>=4.11.0.86",
    "pandas>=2.3.1",
    "tqdm>=4.67.1",
    "ultralytics>=8.3.179",
]
